"""empty message

Revision ID: 2346d961c485
Revises: c103c7edc7ba
Create Date: 2018-04-25 19:44:52.825522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2346d961c485'
down_revision = 'c103c7edc7ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('status', sa.Integer()))
    op.create_unique_constraint(None, 'user', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('order', 'status')
    # ### end Alembic commands ###
