"""empty message

Revision ID: 788060ffa800
Revises: 2346d961c485
Create Date: 2018-05-01 15:53:31.754488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '788060ffa800'
down_revision = '2346d961c485'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('destination', sa.String(length=50), nullable=False, server_default='n/a'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'destination')
    # ### end Alembic commands ###
